// Package notify provides a unified notification interface. Apps
// compose a [Notifier] from one or more [Sender] implementations
// (SMTP, Resend, Postmark, Discord, Slack, webhook, …).
//
// Usage:
//
//	n := notify.New(
//	    notify.WithEmail(smtp.NewSender(smtpOpts)),
//	    notify.WithSlack(slackWebhookURL),
//	)
//	err := n.Send(ctx, notify.Message{
//	    To:      []string{"user@example.com"},
//	    Subject: "Welcome",
//	    HTML:    "<p>Hello</p>",
//	    Text:    "Hello",
//	})
//
// Each Sender is tried in registration order. The first success stops
// the chain. Use [notify.Multi] to fan out to all.
package notify

import (
	"context"
	"fmt"
	"log/slog"
)

// Message is the unified notification payload. Senders ignore fields
// they don't support (e.g. an SMS sender ignores HTML).
type Message struct {
	// To is a list of recipient addresses (email, phone, user ID, …).
	To []string
	// CC / BCC are email-only.
	CC  []string
	BCC []string
	// From overrides the sender default. Optional.
	From    string
	Subject string
	// HTML and Text are email bodies. If only HTML is set, a plain-text
	// version is generated by stripping tags.
	HTML string
	Text string
	// Body is used by non-email senders (Slack, Discord, SMS).
	Body string
	// Attachments are email-only.
	Attachments []Attachment
	// Metadata is passed verbatim to the sender for provider-specific
	// fields (e.g. Resend tags, Postmark message stream).
	Metadata map[string]string
}

// Attachment holds a file to attach to an email.
type Attachment struct {
	Name        string
	ContentType string
	Data        []byte
}

// Sender sends a Message via a specific channel.
type Sender interface {
	Send(ctx context.Context, msg Message) error
	// Name returns a human-readable name for logging.
	Name() string
}

// Notifier holds a set of senders and dispatches messages.
type Notifier struct {
	senders []Sender
	logger  *slog.Logger
}

// Option configures the Notifier.
type Option func(*Notifier)

// WithSender adds a sender.
func WithSender(s Sender) Option {
	return func(n *Notifier) { n.senders = append(n.senders, s) }
}

// New returns a Notifier. At least one sender is recommended; sending
// with no senders is a no-op.
func New(logger *slog.Logger, opts ...Option) *Notifier {
	n := &Notifier{logger: logger}
	for _, o := range opts {
		o(n)
	}
	return n
}

// Send dispatches msg to the first sender that succeeds. Returns the
// last error if all senders fail (or nil if there are no senders).
func (n *Notifier) Send(ctx context.Context, msg Message) error {
	if len(n.senders) == 0 {
		n.logger.WarnContext(ctx, "notify: Send called with no senders registered")
		return nil
	}
	var last error
	for _, s := range n.senders {
		if err := s.Send(ctx, msg); err != nil {
			n.logger.WarnContext(ctx, "notify: sender failed",
				slog.String("sender", s.Name()),
				slog.String("error", err.Error()),
			)
			last = err
			continue
		}
		n.logger.DebugContext(ctx, "notify: sent", slog.String("sender", s.Name()))
		return nil
	}
	return fmt.Errorf("notify: all senders failed: %w", last)
}

// Multi sends msg to ALL registered senders and collects errors.
func (n *Notifier) Multi(ctx context.Context, msg Message) []error {
	var errs []error
	for _, s := range n.senders {
		if err := s.Send(ctx, msg); err != nil {
			n.logger.WarnContext(ctx, "notify: sender failed",
				slog.String("sender", s.Name()),
				slog.String("error", err.Error()),
			)
			errs = append(errs, fmt.Errorf("%s: %w", s.Name(), err))
		}
	}
	return errs
}
