// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
//
// SPDX-License-Identifier: EUPL-1.2

// Package p fetches a build-time tool at a floating version.
package p

//go:generate go run example.com/codegen@latest -out zz_generated.go

// Marker exists so the file declares something.
func Marker() string {
	return "generated by a tool nothing pins"
}
