// SPDX-FileCopyrightText: 2026 lusoris <lusoris@pm.me>
//
// SPDX-License-Identifier: EUPL-1.2

package clikit

import (
	"bytes"
	"errors"
	"fmt"
	"slices"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// MaxCommands bounds the command tree walked by [ManPages] and [Generate].
const MaxCommands = 4096

// ErrTooManyCommands is returned when a tree holds more than [MaxCommands].
var ErrTooManyCommands = errors.New("clikit: command tree exceeds MaxCommands")

// ManOptions fills the man page title line. Every field is optional; Date
// stays empty unless set, which keeps generated pages byte-reproducible.
type ManOptions struct {
	// Section is the manual section (default "1").
	Section string
	// Date is the footer date, e.g. a release date; empty by default.
	Date string
	// Source is the footer source, e.g. "myapp 1.4.0".
	Source string
	// Manual is the header title, e.g. "MyApp Manual".
	Manual string
}

func (o ManOptions) section() string {
	if o.Section == "" {
		return "1"
	}
	return o.Section
}

// roffText escapes the characters man(7) renders specially; see
// groff_man_style(7) "Portability".
var roffText = strings.NewReplacer(
	`\`, `\e`, `-`, `\-`, `'`, `\(aq`, "`", `\(ga`, `^`, `\(ha`, `~`, `\(ti`, `"`, `\(dq`,
)

// ManPages renders one man(7) page per available command of root, keyed by
// "man/man<section>/<command-path>.<section>". Hidden, deprecated and help
// commands are skipped; aliases and [EnumFlag] values are listed.
func ManPages(root *cobra.Command, opts ManOptions) (map[string][]byte, error) {
	cmds, err := manCommands(root)
	if err != nil {
		return nil, err
	}
	out := make(map[string][]byte, len(cmds))
	section := opts.section()
	for _, c := range cmds {
		out["man/man"+section+"/"+dashed(c)+"."+section] = renderMan(c, opts)
	}
	return out, nil
}

// manCommands walks the tree breadth-first without recursion (HISS-01).
func manCommands(root *cobra.Command) ([]*cobra.Command, error) {
	if root == nil {
		return nil, errors.New("clikit: man: nil root command")
	}
	root.InitDefaultCompletionCmd()
	queue := []*cobra.Command{root}
	for i := 0; i < len(queue) && i < MaxCommands; i++ {
		queue[i].InitDefaultHelpFlag()
		queue = append(queue, documented(queue[i])...)
	}
	if len(queue) > MaxCommands {
		return nil, fmt.Errorf("%w (%d)", ErrTooManyCommands, MaxCommands)
	}
	return queue, nil
}

// documented returns c's children that get a page, sorted by name.
func documented(c *cobra.Command) []*cobra.Command {
	kids := make([]*cobra.Command, 0, len(c.Commands()))
	for _, k := range c.Commands() {
		if k.IsAvailableCommand() && !k.IsAdditionalHelpTopicCommand() {
			kids = append(kids, k)
		}
	}
	slices.SortFunc(kids, func(a, b *cobra.Command) int { return strings.Compare(a.Name(), b.Name()) })
	return kids
}

func dashed(c *cobra.Command) string { return strings.ReplaceAll(c.CommandPath(), " ", "-") }

func renderMan(c *cobra.Command, opts ManOptions) []byte {
	var b bytes.Buffer
	b.WriteString(".\\\" Code generated by golusoris core/clikit. DO NOT EDIT.\n")
	fmt.Fprintf(&b, ".TH %s %s %s %s %s\n", roffArg(strings.ToUpper(dashed(c))), roffArg(opts.section()),
		roffArg(opts.Date), roffArg(opts.Source), roffArg(opts.Manual))
	b.WriteString(".SH NAME\n" + roffEsc(dashed(c)) + ` \- ` + roffLine(c.Short) + "\n")
	b.WriteString(".SH SYNOPSIS\n\\fB" + roffEsc(c.CommandPath()) + "\\fR" +
		roffEsc(strings.TrimPrefix(c.UseLine(), c.CommandPath())) + "\n")
	desc := c.Long
	if desc == "" {
		desc = c.Short
	}
	b.WriteString(".SH DESCRIPTION\n" + roffBlock(desc))
	if len(c.Aliases) > 0 {
		b.WriteString(".SH ALIASES\n" + roffBlock(strings.Join(c.Aliases, ", ")))
	}
	writeFlags(&b, "OPTIONS", c.NonInheritedFlags())
	writeFlags(&b, "OPTIONS INHERITED FROM PARENT COMMANDS", c.InheritedFlags())
	if c.Example != "" {
		b.WriteString(".SH EXAMPLES\n.EX\n" + roffBlock(c.Example) + ".EE\n")
	}
	writeSeeAlso(&b, c, opts.section())
	return b.Bytes()
}

func writeFlags(b *bytes.Buffer, title string, flags *pflag.FlagSet) {
	if !flags.HasAvailableFlags() {
		return
	}
	b.WriteString(".SH " + roffArg(title) + "\n")
	flags.VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Deprecated != "" {
			return
		}
		varname, usage := pflag.UnquoteUsage(f)
		b.WriteString(".TP\n" + flagTag(f, varname) + "\n" + roffBlock(usage))
		if values := f.Annotations[enumAnnotation]; len(values) > 0 {
			b.WriteString(".br\nValues: " + roffLine(strings.Join(values, ", ")) + "\n")
		}
		if def, ok := flagDefault(f); ok {
			b.WriteString(".br\nDefault: " + roffLine(def) + "\n")
		}
	})
}

// flagTag renders "-s, --name value" in man(7) style: bold names, italic
// placeholder, optional value in brackets.
func flagTag(f *pflag.Flag, varname string) string {
	tag := `\fB\-\-` + roffEsc(f.Name) + `\fR`
	if f.Shorthand != "" && f.ShorthandDeprecated == "" {
		tag = `\fB\-` + roffEsc(f.Shorthand) + `\fR, ` + tag
	}
	switch {
	case varname == "":
		return tag
	case f.NoOptDefVal != "":
		return tag + `[=\fI` + roffEsc(varname) + `\fR]`
	default:
		return tag + ` \fI` + roffEsc(varname) + `\fR`
	}
}

// flagDefault mirrors pflag's help: zero defaults are omitted, strings quoted.
func flagDefault(f *pflag.Flag) (string, bool) {
	if f.Value.Type() == "string" {
		return fmt.Sprintf("%q", f.DefValue), f.DefValue != ""
	}
	switch f.DefValue {
	case "", "false", "0", "0s", "<nil>", "[]":
		return "", false
	}
	return f.DefValue, true
}

func writeSeeAlso(b *bytes.Buffer, c *cobra.Command, section string) {
	refs := make([]string, 0, len(c.Commands())+1)
	if c.HasParent() {
		refs = append(refs, manRef(c.Parent(), section))
	}
	for _, k := range documented(c) {
		refs = append(refs, manRef(k, section))
	}
	if len(refs) > 0 {
		b.WriteString(".SH SEE ALSO\n" + strings.Join(refs, ", ") + "\n")
	}
}

func manRef(c *cobra.Command, section string) string {
	return `\fB` + roffEsc(dashed(c)) + `\fR(` + roffEsc(section) + ")"
}

func roffEsc(s string) string { return roffText.Replace(s) }

// roffLine escapes text that must stay on one input line.
func roffLine(s string) string { return roffEsc(strings.Join(strings.Fields(s), " ")) }

// roffArg quotes a macro argument; roffText already turned `"` into \(dq.
func roffArg(s string) string { return `"` + roffLine(s) + `"` }

// roffBlock renders free text line by line: blank lines become paragraph
// breaks and a leading dot is defused so no line parses as a request.
func roffBlock(s string) string {
	if strings.TrimSpace(s) == "" {
		return ""
	}
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		line = strings.TrimRight(line, " \t")
		switch {
		case line == "":
			b.WriteString(".sp\n")
		case line[0] == '.':
			b.WriteString(`\&` + roffEsc(line) + "\n")
		default:
			b.WriteString(roffEsc(line) + "\n")
		}
	}
	return b.String()
}
