// Package graphql wires a gqlgen [*handler.Server] as an fx dependency.
// Apps supply a [graphql.ExecutableSchema] (generated by gqlgen) and this
// module adds transports, extensions, and mounts the server + playground on a
// [chi.Router].
//
// Usage:
//
//	fx.New(
//	    golusoris.Core,
//	    httpx_router.Module,
//	    httpx_server.Module,
//	    graphql.Module,
//	    fx.Provide(func() gql.ExecutableSchema { return generated.NewExecutableSchema(...) }),
//	)
//
// The GraphQL endpoint is mounted at Config.Path (default "/graphql").
// The GraphiQL playground is mounted at Config.PlaygroundPath (default "/graphql/playground"),
// and can be disabled by setting graphql.playground to false.
//
// Config keys (env: APP_GRAPHQL_*):
//
//	graphql.path              # GraphQL endpoint path (default: /graphql)
//	graphql.playground        # enable GraphiQL playground (default: true)
//	graphql.playground_path   # playground path (default: /graphql/playground)
//	graphql.complexity_limit  # max query complexity, 0 disables (default: 1000)
//	graphql.apq_cache         # APQ LRU cache size, 0 disables APQ (default: 100)
package graphql

import (
	"fmt"
	"net/http"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/handler/extension"
	"github.com/99designs/gqlgen/graphql/handler/lru"
	"github.com/99designs/gqlgen/graphql/handler/transport"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/go-chi/chi/v5"
	"go.uber.org/fx"

	"github.com/golusoris/golusoris/config"
)

const (
	defaultPath           = "/graphql"
	defaultPlaygroundPath = "/graphql/playground"
	defaultComplexity     = 1000
	defaultAPQCache       = 100
)

// Config holds GraphQL server configuration.
type Config struct {
	// Path is the HTTP path for the GraphQL endpoint (default: /graphql).
	Path string `koanf:"path"`
	// Playground enables the GraphiQL playground (default: true).
	Playground bool `koanf:"playground"`
	// PlaygroundPath is the HTTP path for the playground UI (default: /graphql/playground).
	PlaygroundPath string `koanf:"playground_path"`
	// ComplexityLimit caps query complexity (0 disables; default: 1000).
	ComplexityLimit int `koanf:"complexity_limit"`
	// APQCache is the LRU size for Automatic Persisted Queries (0 disables APQ; default: 100).
	APQCache int `koanf:"apq_cache"`
}

// DefaultConfig returns a safe default configuration.
func DefaultConfig() Config {
	return Config{
		Path:            defaultPath,
		Playground:      true,
		PlaygroundPath:  defaultPlaygroundPath,
		ComplexityLimit: defaultComplexity,
		APQCache:        defaultAPQCache,
	}
}

func (c Config) withDefaults() Config {
	if c.Path == "" {
		c.Path = defaultPath
	}
	if c.PlaygroundPath == "" {
		c.PlaygroundPath = defaultPlaygroundPath
	}
	if c.ComplexityLimit == 0 {
		c.ComplexityLimit = defaultComplexity
	}
	if c.APQCache == 0 {
		c.APQCache = defaultAPQCache
	}
	return c
}

// Module provides a configured *handler.Server and mounts it on a chi.Router.
// Requires a graphql.ExecutableSchema, chi.Router, and *config.Config in the fx graph.
var Module = fx.Module("golusoris.graphql",
	fx.Provide(loadConfig),
	fx.Provide(newServer),
	fx.Invoke(mountRoutes),
)

func loadConfig(cfg *config.Config) (Config, error) {
	c := Config{}
	if err := cfg.Unmarshal("graphql", &c); err != nil {
		return Config{}, fmt.Errorf("graphql: load config: %w", err)
	}
	// Playground defaults to true; koanf zero-value is false, so only apply
	// the default when the key was not explicitly set.
	if c.Path == "" && c.PlaygroundPath == "" && !c.Playground {
		c.Playground = true
	}
	return c.withDefaults(), nil
}

// newServer builds the gqlgen handler with all standard transports + extensions.
func newServer(schema graphql.ExecutableSchema, cfg Config) *handler.Server {
	srv := handler.New(schema)

	// Transports (order matters: first match wins for the request type).
	srv.AddTransport(transport.Websocket{})
	srv.AddTransport(transport.SSE{})
	srv.AddTransport(transport.Options{})
	srv.AddTransport(transport.GET{})
	srv.AddTransport(transport.POST{})
	srv.AddTransport(transport.MultipartForm{})

	// Extensions.
	srv.Use(extension.Introspection{})
	if cfg.APQCache > 0 {
		srv.Use(extension.AutomaticPersistedQuery{Cache: lru.New[string](cfg.APQCache)})
	}
	if cfg.ComplexityLimit > 0 {
		srv.Use(extension.FixedComplexityLimit(cfg.ComplexityLimit))
	}

	return srv
}

// mountRoutes registers the GraphQL endpoint and optional playground on r.
func mountRoutes(r chi.Router, srv *handler.Server, cfg Config) {
	r.Handle(cfg.Path, srv)
	if cfg.Playground {
		r.Get(cfg.PlaygroundPath, playground.Handler("GraphiQL", cfg.Path))
	}
}

// Handler returns an http.Handler suitable for use outside chi
// (e.g. mounting on an existing mux).
func Handler(srv *handler.Server) http.Handler { return srv }
