// Package ebpf provides an fx-wired scaffold for loading and managing eBPF
// programs using [cilium/ebpf].
//
// # Linux only
//
// eBPF requires a Linux kernel ≥ 5.7 with CAP_BPF (or CAP_SYS_ADMIN).
// On non-Linux platforms the module is a no-op stub.
//
// # Workflow
//
//  1. Write eBPF C source (e.g. bpf/xdp_drop.c).
//  2. Compile with clang: clang -O2 -target bpf -c bpf/xdp_drop.c -o bpf/xdp_drop.o
//  3. Generate Go bindings: go generate ./ebpf/...  (calls go run github.com/cilium/ebpf/cmd/bpf2go)
//  4. Supply an [ObjectProvider] that returns the compiled .o bytes.
//  5. Register [Loader] callbacks via [Registry.Register] to attach programs to
//     kernel hooks using the link sub-package.
//
// Usage:
//
//	fx.New(
//	    ebpf.Module,
//	    fx.Provide(func() ebpf.ObjectProvider {
//	        return ebpf.BytesProvider(bpfObjects) // generated bytes from bpf2go
//	    }),
//	    fx.Invoke(func(reg *ebpf.Registry) {
//	        reg.Register("xdp_drop", func(coll *ebpf.Collection) error {
//	            prog := coll.Programs["xdp_drop"]
//	            l, err := link.AttachXDP(link.XDPOptions{
//	                Program:   prog,
//	                Interface: ifindex,
//	            })
//	            // store l somewhere to keep it alive
//	            return err
//	        })
//	    }),
//	)
package ebpf

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"

	"github.com/cilium/ebpf"
	"go.uber.org/fx"
)

// ObjectProvider returns the raw ELF bytes of a compiled eBPF object file.
type ObjectProvider func() ([]byte, error)

// BytesProvider returns an [ObjectProvider] that serves fixed bytes.
func BytesProvider(data []byte) ObjectProvider {
	return func() ([]byte, error) { return data, nil }
}

// Loader is called after the eBPF collection is loaded, receiving the
// collection so that programs can be attached to kernel hooks.
type Loader func(coll *ebpf.Collection) error

// Registry holds named [Loader] callbacks that are invoked on fx Start.
type Registry struct {
	loaders []namedLoader
}

type namedLoader struct {
	name string
	fn   Loader
}

// Register adds a named Loader to the registry.
func (r *Registry) Register(name string, fn Loader) {
	r.loaders = append(r.loaders, namedLoader{name: name, fn: fn})
}

// Module provides *Registry into the fx graph and loads the eBPF collection
// on fx Start.  Requires an ObjectProvider and *slog.Logger.
var Module = fx.Module("golusoris.ebpf",
	fx.Provide(newRegistry),
	fx.Invoke(startLoader),
)

type params struct {
	fx.In
	LC       fx.Lifecycle
	Registry *Registry
	Provider ObjectProvider
	Logger   *slog.Logger
}

func newRegistry() *Registry { return &Registry{} }

func startLoader(p params) {
	p.LC.Append(fx.Hook{
		OnStart: func(_ context.Context) error {
			data, err := p.Provider()
			if err != nil {
				return fmt.Errorf("ebpf: object provider: %w", err)
			}
			spec, err := ebpf.LoadCollectionSpecFromReader(bytes.NewReader(data))
			if err != nil {
				return fmt.Errorf("ebpf: load spec: %w", err)
			}
			coll, err := ebpf.NewCollection(spec)
			if err != nil {
				return fmt.Errorf("ebpf: new collection: %w", err)
			}
			for _, l := range p.Registry.loaders {
				if err := l.fn(coll); err != nil {
					coll.Close()
					return fmt.Errorf("ebpf: loader %s: %w", l.name, err)
				}
				p.Logger.Info("ebpf: program attached", "loader", l.name)
			}
			return nil
		},
	})
}
